/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WPointGreyApp */

#ifndef _Included_WPointGreyApp
#define _Included_WPointGreyApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WPointGreyApp
 * Method:    initContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_initContext
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_connect
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    getNumCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_WPointGreyApp_getNumCamera
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    printCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_printCamera
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    startCapture
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_startCapture
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     WPointGreyApp
 * Method:    startVideo
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_startVideo
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     WPointGreyApp
 * Method:    stopCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_stopCapture
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    calibrageCouleur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_calibrageCouleur
  (JNIEnv *, jobject);

/*
 * Class:     WPointGreyApp
 * Method:    destroysContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WPointGreyApp_destroysContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
